# Generated by Django 4.1 on 2022-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Course ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Description')),
            ],
        ),
    ]
